Реализовано добавление Jobs из crowleer
Biotech-h/crowleer pull request #2
Opened 2022-06-30 17:43 UTC by IrinaSafenkova

Реализовано добавление Jobs из crowleer

2022-06-30 19:07 UTC, vppuzakov requested changes

2022-06-30 19:07 UTC, vppuzakov commented on crowleer/__main__.py
> +    transfer_jobs = [client_job.add(job) for job in jobs]
Нам результат добавления не важен, поэтому можно не присваивать значения

Так же не очень здорово выполнять метод, который ходит куда-либо (в апишку, в базу) внутри list comprehension - лучше переписать с обычным циклом

2022-06-30 19:07 UTC, vppuzakov commented on pyproject.toml
> +Flask = "^2.1.2"
flask кажется здесь лишний, зависимости, которые не используются - не ставим

poetry remove flask

2022-06-30 19:07 UTC, vppuzakov commented on crowleer/api/schemas.py
> +class JobModel(BaseModel):
Лучше назвать Job(BaseModel) - не нужен нам этот суффикс

2022-06-30 19:07 UTC, vppuzakov commented on crowleer/api/schemas.py
> +class CompanyModel(BaseModel):
Тоже давай переименуем

2022-06-30 19:07 UTC, vppuzakov commented on crowleer/api/schemas.py
> +    class Config:
Не уверен используем ли мы здесь from_orm - если нет - то удалить

2022-06-30 19:07 UTC, vppuzakov commented on crowleer/api/jobs.py
> +client_job = JobApi()
Давай вынесем в один класс client где будет и jobs и companies

```python
class ApiClient:
    def __init__(self) -> None:
        self.jobs = JobApi()
        self.companies = CompanyApi()

client = ApiClient()
```

2022-06-30 19:07 UTC, vppuzakov commented on crowleer/api/jobs.py
> +        respose = request.post('/api/v1/company/jobs', content=json_job, headers=headers)
все верно, только вот куда делается запрос? на какой сервер? - не хватает части `http://ipaddress:port`

2022-06-30 19:07 UTC, vppuzakov commented on crowleer/api/companies.py
> +        respose = request.post('/api/v1/jobs/', content=json_company, headers=headers)
не хватает адреса хоста и протокола

2022-06-30 22:35 UTC, IrinaSafenkova commented on pyproject.toml
> +Flask = "^2.1.2"
а как тогда лучше поступить с request, который был импортирован из flask? импортировать вместо этого requests?

2022-07-01 05:52 UTC, vppuzakov commented on pyproject.toml
> +Flask = "^2.1.2"
flask.request - только на бэкенде используется - содержит входящий запрос
pip install requests - отдельная библиотека и мы ее тут не используем - у нас httpx

2022-07-01 05:57 UTC, vppuzakov approved these changes

2022-07-01 05:57 UTC, vppuzakov commented on crowleer/__main__.py
> +        client.jobs.add(job)
👍

2022-07-01 05:57 UTC, vppuzakov commented on crowleer/api/client.py
> +class ApiClient:
👍

2022-07-01 05:57 UTC, vppuzakov commented on crowleer/api/companies.py
> +        respose = requests.post(f'{config.app_host}:{config.app_port}/api/v1/company/', content=json_company, headers=headers)
💡 чтобы в каждом клиенте не зависеть от config - лучше передать base_url нашего бэкенда в сам класс через init конструктор и уже использовать его

2022-07-01 05:57 UTC, vppuzakov commented on crowleer/config.py
> +    app_host: str
💡 нам нужен `backend_url: str`
примерно такого вида:
`http://localhost:8080`

2022-07-01 05:57 UTC, vppuzakov commented on pyproject.toml
> +requests = "^2.28.1"
requests удали - нигде ж не используется

2022-07-01 07:07 UTC, merged